[DEFAULT]
; set your path to where everything is saved
MY_PATH = /home/steven

stats_name    = cosebis
CSL_PATH      = %(MY_PATH)s/cosmosis-standard-library/
PROJECT_PATH  = %(MY_PATH)s/Work/cosmosis_stuff/thesis_config
KCAP_PATH     = %(PROJECT_PATH)s/kcap_modules/
MOD_PATH      = %(MY_PATH)s/Work/cosmosis_stuff/mod/
COSEBIS_PATH  = %(MY_PATH)s/cosmosis-standard-library/shear/cosebis/

OUTPUT_FOLDER = %(PROJECT_PATH)s/outputs/
;INPUT_FOLDER  = %(PROJECT_PATH)s/inputs/
CONFIG_FOLDER = %(PROJECT_PATH)s/config/
;data_file     = %(INPUT_FOLDER)s/cosebis_KIDS1000_BlindC_with_m_bias_V1.0.0A_ugriZYJHKs_photoz_SG_mask_LF_svn_309c_2Dbins_v2_goldclasses_Flag_SOM_Fid.fits
;redshift_name = source  

SAMPLER_NAME  = test
RUN_NAME 	  = %(SAMPLER_NAME)s

;bandpower_folder = %(MY_PATH)s/bandpowers_weights/

; ;COSEBIs settings
tmin_cosebis = 0.50
tmax_cosebis = 300.00
nmax_cosebis = 5

;WnLogPath = %(MY_PATH)s/WnLog/
WnLogPath = %(MY_PATH)s/WnLog/

[test]
save_dir = output/test
fatal_errors = T

[pipeline]
modules = camb
values  = %(CONFIG_FOLDER)s/values.ini

; extra_output = cosmological_parameters/S_8 cosmological_parameters/A_s cosmological_parameters/omega_c 
;                 cosmological_parameters/omega_nu cosmological_parameters/omega_lambda 
;                 cosmological_parameters/cosmomc_theta nofz_shifts/bias_1 nofz_shifts/bias_2 
;                 nofz_shifts/bias_3 nofz_shifts/bias_4 nofz_shifts/bias_5 delta_z_out/bin_1 
;                 delta_z_out/bin_2 delta_z_out/bin_3 delta_z_out/bin_4 delta_z_out/bin_5 

likelihoods  = 

timing = T
debug = T

[runtime]
sampler = %(SAMPLER_NAME)s

[output]
filename = %(OUTPUT_FOLDER)s/output_%(RUN_NAME)s.txt
format = text

[emcee]
walkers = 32
nsteps = 1
samples = 2

[multinest]
max_iterations=2
multinest_outfile_root= %(OUTPUT_FOLDER)s
resume=T
tolerance = 0.01
constant_efficiency = F
live_points = 1000
efficiency = 0.3

[camb]
file = %(CSL_PATH)s/boltzmann/camb/camb_interface.py
do_reionization = F
; mode must be one of the following 'background', 'thermal', 'cmb', 'power', 'all' (previously it was set to mode=transfer)
mode = power
nonlinear = pk
halofit_version = mead2020_feedback
neutrino_hierarchy = normal
kmax = 20.0
zmid = 4.5 ;original : 2.0
nz_mid = 100
zmax = 6.0
zmin = 3.0 ;original : none
nz = 150
background_zmax = 6.0
background_zmin = 3.0 ;original : 0
background_nz = 6000

[likelihood]
file = %(KCAP_PATH)s/utils/mini_like.py
input_section_name = scale_cuts_output
like_name = loglike