; [chebyshev_coefficients]
; c0 = gaussian  1.307  0.021
; c1 = gaussian -0.282  0.029
; c2 = gaussian  0.021  0.015

[uncorr_chebyshev_coefficients]
; SN
; c0 = gaussian 24.49625109   1.0
; c1 = gaussian 248.81930777  1.0
; c2 = gaussian 229.88541429  1.0

; SN + BAO
; c0 = gaussian 52.77217502   1.0
; c1 = gaussian 333.26212524  1.0
; c2 = gaussian 178.70766496  1.0

; SN + BAO + QSO
c0 = gaussian 94.82648446   1.0
c1 = gaussian 370.23868677  1.0

; SN + BAO + CMB
; c0 = gaussian 91.94624081   1.0
; c1 = gaussian 371.64984302  1.0

; SN + BAO + CMB + QSO
; c0 = gaussian 91.94642035   1.0
; c1 = gaussian 372.09386794  1.0

[nofz_shifts]
uncorr_bias_1 = gaussian  0.000  1.0
uncorr_bias_2 = gaussian -0.181  1.0
uncorr_bias_3 = gaussian -1.110  1.0
uncorr_bias_4 = gaussian -1.395  1.0
uncorr_bias_5 = gaussian  1.265  1.0

; [cosmological_parameters]
; omch2 = gaussian 0.1174 0.0033 ; Marie

; from SOM KV450 paper: https://arxiv.org/pdf/1909.09632.pdf table 3.
; ∆z = z_est − z_true = 0.0  0.002 0.013 0.011 −0.006

; in cosmosis we have nz_biased = f(z - bias). Which means that delta_z= z_true - z_est
; so delta_z = 0.0 -0.002 -0.013 -0.011 0.006

