[runtime]
sampler = test
root = ${PWD}
resume = T

[test]
save_dir = output/cfhtlens
fatal_errors = T

[pipeline]
modules = consistency  camb  load_nz  shear_shear  2pt  cfhtlens
values = examples/cfhtlens_values.ini

[consistency]
file = utility/consistency/consistency_interface.py
verbose = F

[camb]
file = boltzmann/camb/camb_interface.py

; This means to calculate everything
; including matter power
mode = all
lmax = 2500

; You would set this to zero during an MCMC
; run to avoid too much line noise
feedback=2

; This means to get non-linear P(k), but
; not bother with non-linear CMB lensing
NonLinear = pk

; These choices values should be explored
; to check for convergence
kmax = 10.0
kmax_extrapolate = 500.0
nk = 100
zmin = 0.0
zmax = 3.0
nz = 100

[load_nz]
file = number_density/load_nz_fits/load_nz_fits.py
nz_file = likelihood/cfhtlens/cfhtlens_heymans13.fits
data_sets = SAMPLE

[shear_shear]
file = structure/projection/project_2d.py
shear-shear = sample-sample
verbose = T
ell_min_logspaced = 20.0
ell_max_logspaced = 10000.0
n_ell_logspaced = 220

[2pt]
file = shear/cl_to_xi_nicaea/nicaea_interface.so
corr_type = 0

[cfhtlens]
file = likelihood/2pt/2pt_like.py
data_file = likelihood/cfhtlens/cfhtlens_heymans13.fits

like_name = cfhtlens
data_sets = xi_plus xi_minus

covariance_realizations = 1656

angle_range_xi_plus_1_1 = 2.0  999999.0
angle_range_xi_plus_1_2 = 2.0  999999.0
angle_range_xi_plus_1_3 = 2.0  999999.0
angle_range_xi_plus_1_4 = 2.0  999999.0
angle_range_xi_plus_1_5 = 2.0  999999.0
angle_range_xi_plus_1_6 = 2.0  999999.0
angle_range_xi_plus_2_2 = 2.0  999999.0
angle_range_xi_plus_2_3 = 2.0  999999.0
angle_range_xi_plus_2_4 = 2.0  999999.0
angle_range_xi_plus_2_5 = 2.0  999999.0
angle_range_xi_plus_2_6 = 2.0  999999.0
angle_range_xi_plus_3_3 = 2.0  999999.0
angle_range_xi_plus_3_4 = 2.0  999999.0
angle_range_xi_plus_3_5 = 2.0  999999.0
angle_range_xi_plus_3_6 = 2.0  999999.0
angle_range_xi_plus_4_4 = 2.0  999999.0
angle_range_xi_plus_4_5 = 2.0  999999.0
angle_range_xi_plus_4_6 = 2.0  999999.0
angle_range_xi_plus_5_5 = 2.0  999999.0
angle_range_xi_plus_5_6 = 2.0  999999.0
angle_range_xi_plus_6_6 = 2.0  999999.0

angle_range_xi_minus_1_1 = 2.0  999999.0
angle_range_xi_minus_1_2 = 2.0  999999.0
angle_range_xi_minus_1_3 = 2.0  999999.0
angle_range_xi_minus_1_4 = 2.0  999999.0
angle_range_xi_minus_1_5 = 2.0  999999.0
angle_range_xi_minus_1_6 = 2.0  999999.0
angle_range_xi_minus_2_2 = 2.0  999999.0
angle_range_xi_minus_2_3 = 2.0  999999.0
angle_range_xi_minus_2_4 = 2.0  999999.0
angle_range_xi_minus_2_5 = 2.0  999999.0
angle_range_xi_minus_2_6 = 2.0  999999.0
angle_range_xi_minus_3_3 = 2.0  999999.0
angle_range_xi_minus_3_4 = 2.0  999999.0
angle_range_xi_minus_3_5 = 2.0  999999.0
angle_range_xi_minus_3_6 = 2.0  999999.0
angle_range_xi_minus_4_4 = 2.0  999999.0
angle_range_xi_minus_4_5 = 2.0  999999.0
angle_range_xi_minus_4_6 = 2.0  999999.0
angle_range_xi_minus_5_5 = 2.0  999999.0
angle_range_xi_minus_5_6 = 2.0  999999.0
angle_range_xi_minus_6_6 = 2.0  999999.0
