[DEFAULT]
; set your path to where everything is saved
MY_PATH = /home/steven/thesis
; MY_PATH = /pfs/data6/home/hd/hd_hd/hd_bs307/thesis

CSL_PATH      = %(MY_PATH)s/cosmosis-standard-library/
; CSL_PATH      = /home/steven/cosmosis-standard-library/
PROJECT_PATH  = %(MY_PATH)s/thesis_config
KCAP_PATH     = %(PROJECT_PATH)s/kcap_modules/
MOD_PATH      = %(MY_PATH)s/mod/
COSEBIS_PATH  = %(MY_PATH)s/cosmosis-standard-library/shear/cosebis/

OUTPUT_FOLDER = %(PROJECT_PATH)s/outputs/run_cluster16_WL_only_KIDS_VALUES/
INPUT_FOLDER  = %(PROJECT_PATH)s/inputs/
CONFIG_FOLDER = %(PROJECT_PATH)s/config/
data_file     = %(INPUT_FOLDER)s/test6_cosebis_KIDS1000_BlindC_with_m_bias_V1.0.0A_ugriZYJHKs_photoz_SG_mask_LF_svn_309c_2Dbins_v2_goldclasses_Flag_SOM_Fid.fits
redshift_name = source  

SAMPLER_NAME  = multinest
RUN_NAME      = %(SAMPLER_NAME)s

;bandpower_folder = %(MY_PATH)s/bandpowers_weights/

; ;COSEBIs settings
tmin_cosebis = 60.0
tmax_cosebis = 300.00
nmax_cosebis = 5

;WnLogPath = %(MY_PATH)s/WnLog/
WnLogPath = %(MY_PATH)s/WnLog/

; Parameters for the pipeline
model_exponent = -1   ; The exponent in the model-independent expansion function
nz_z_cut = 6.0     ; Redshift cut for load_nz_fits
z_mid = 2.0
z_max = 6.0
pm = %(INPUT_FOLDER)s/pm_lin_kids_real.txt
; pm = %(INPUT_FOLDER)s/pm_lin_no_mid.txt
; pm = %(INPUT_FOLDER)s/pm_lin_no_mid_z2.txt
; pm = %(INPUT_FOLDER)s/pm_kids_mid6.txt
; pm = %(INPUT_FOLDER)s/pm_lin_kids_z2.txt
cheb_cov_file = %(INPUT_FOLDER)s/test.txt

[apriori]
nsample = 2000

[test]
save_dir = output/tester
fatal_errors = T

[pipeline]
modules = ; sample_S8 
        ; sigma8toAs
        ; camb
        ; pos_expf
        ; mycamb
        ; testing_output
        ; sample_corr_cheb
        distance_mod
        matter_power
        extrapolate_power
        ; k015
        load_nz_fits
        correlated_dz_priors
	source_photoz_bias 
	linear_alignment 
        projection
	cosebis 
	scale_cuts
        ; testing_output
	likelihood        
         
values  = %(CONFIG_FOLDER)s/values.ini
priors  = %(CONFIG_FOLDER)s/priors.ini

; extra_output = cosmological_parameters/S_8 cosmological_parameters/A_s cosmological_parameters/omega_c 
;                 cosmological_parameters/omega_nu cosmological_parameters/omega_lambda 
;                 cosmological_parameters/cosmomc_theta nofz_shifts/bias_1 nofz_shifts/bias_2 
;                 nofz_shifts/bias_3 nofz_shifts/bias_4 nofz_shifts/bias_5 delta_z_out/bin_1 
;                 delta_z_out/bin_2 delta_z_out/bin_3 delta_z_out/bin_4 delta_z_out/bin_5 

likelihoods  = loglike

timing = T
debug = T

[runtime]
sampler = %(SAMPLER_NAME)s

[output]
filename = %(OUTPUT_FOLDER)s/output_%(RUN_NAME)s.txt
format = text

[emcee]
walkers = 32
nsteps = 1
samples = 2

[multinest]
max_iterations=3000
multinest_outfile_root= %(OUTPUT_FOLDER)s
resume=T
tolerance = 0.01
constant_efficiency = F
live_points = 100
efficiency = 0.3

[sample_corr_cheb]
file = %(MOD_PATH)s/sample_corr_cheb.py
cov_file = %(cheb_cov_file)s

[load_nz_fits]
file = %(CSL_PATH)s/number_density/load_nz_fits/load_nz_fits.py
nz_file = %(data_file)s
data_sets = %(redshift_name)s
z_cut = %(nz_z_cut)s

[distance_mod]
file = %(MOD_PATH)s/distance_mod.py
z = %(INPUT_FOLDER)s/z_kids.txt
zmax = 6.0 ;%(z_max)s
zmid = 2.0
zmin = 0.0
nz_mid = 100
nz = 150
background_zmax = 6.0
background_zmin = 0.0
background_nz = 25000 ;6000?
method = inv_cheb  # lcdm, pca, inv_cheb
exponent = %(model_exponent)s

[matter_power]
file = %(MOD_PATH)s/matter_power.py
kmax = 20.0
pm0 = %(pm)s

k_h = %(INPUT_FOLDER)s/k_pre_ext.txt

[projection]
file = %(CSL_PATH)s/structure/projection/project_2d.py
ell_min_logspaced = 1.0
ell_max_logspaced = 1.0e4
n_ell_logspaced = 50
position-shear = F
fast-shear-shear-ia = %(redshift_name)s-%(redshift_name)s
verbose = F
get_kernel_peaks = F

[likelihood]
file = %(KCAP_PATH)s/utils/mini_like.py
theory60 = %(INPUT_FOLDER)s/theory60.txt
input_section_name = scale_cuts_output
like_name = loglike

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[camb]
file = %(CSL_PATH)s/boltzmann/camb/camb_interface.py
do_reionization = F
; mode must be one of the following 'background', 'thermal', 'cmb', 'power', 'all' (previously it was set to mode=transfer)
mode = power
nonlinear = none ; pk/none
halofit_version = mead2020_feedback
neutrino_hierarchy = normal
kmax = 20.0 ;20.0
zmid = 2.0
nz_mid = 100
zmax = 6.0
nz = 150
background_zmax = 6.0
background_zmin = 0.0
background_nz = 6000

[mycamb]
file = %(MOD_PATH)s/mycamb.py
kmax = 500.0
zmid = 2.0
nz_mid = 100
zmax = 6.0
nz = 150
zmin=0.0

[sample_S8]
file = %(KCAP_PATH)s/utils/sample_S8.py
s8_name = s_8_input

[sigma8toAs]
file = %(KCAP_PATH)s/utils/sigma8toAs.py

[correlated_dz_priors]
file = %(KCAP_PATH)s/utils/correlated_priors.py
uncorrelated_parameters = nofz_shifts/uncorr_bias_1 nofz_shifts/uncorr_bias_2 nofz_shifts/uncorr_bias_3 nofz_shifts/uncorr_bias_4 nofz_shifts/uncorr_bias_5
output_parameters = nofz_shifts/bias_1 nofz_shifts/bias_2 nofz_shifts/bias_3 nofz_shifts/bias_4 nofz_shifts/bias_5
covariance = %(INPUT_FOLDER)s/SOM_cov_multiplied.asc

[source_photoz_bias]
file = %(CSL_PATH)s/number_density/photoz_bias/photoz_bias.py
mode = additive
sample = nz_%(redshift_name)s
bias_section  = nofz_shifts
interpolation = cubic
output_deltaz = T
output_section_name = delta_z_out

[extrapolate_power]
file = %(CSL_PATH)s/boltzmann/extrapolate/extrapolate_power.py
kmax = 500.0

[linear_alignment]
file = %(CSL_PATH)s/intrinsic_alignments/la_model/linear_alignments_interface.py
method = linear ;linear/bk_corrected

[cosebis]
file = %(COSEBIs_PATH)s/cl_to_cosebis/cl_to_cosebis_interface.so
theta_min = %(tmin_cosebis)s
theta_max = %(tmax_cosebis)s
n_max = %(nmax_cosebis)s
Roots_n_Norms_FolderName = %(COSEBIS_PATH)s/TLogsRootsAndNorms/
Wn_Output_FolderName = %(WnLogPath)s
Tn_Output_FolderName = %(COSEBIS_PATH)s/TpnLog/
output_section_name =  cosebis

[scale_cuts]
file = %(KCAP_PATH)s/scale_cuts/scale_cuts.py
output_section_name = scale_cuts_output
data_and_covariance_fits_filename = %(data_file)s
use_stats = En
keep_ang_En   = 0.5 5.5 
xi_plus_extension_name = xiP
xi_minus_extension_name = xiM
bandpower_ggl_extension_name = PneE
bandpower_e_cosmic_shear_extension_name = PeeE
cosebis_extension_name = En
xi_plus_section_name = shear_xi_plus_binned
xi_minus_section_name = shear_xi_minus_binned
bandpower_ggl_section_name = bandpower_galaxy_shear
bandpower_e_cosmic_shear_section_name = bandpower_shear_e
cosebis_section_name = cosebis
simulate = F
simulate_with_noise = F

[testing_output]
file = %(MOD_PATH)s/testing_output.py

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[distance_mod2]
file = %(MOD_PATH)s/distance_mod2.py
z = %(INPUT_FOLDER)s/z_kids.txt
zmax = 6.0
zmid = 2.0
zmin = 0.0
nz_mid = 100
nz = 150
background_zmax = 6.0
background_zmin = 0.0
background_nz = 150 ;6000?

[matter_power2]
file = %(MOD_PATH)s/matter_power2.py
k_h = %(INPUT_FOLDER)s/k_pre_ext.txt

[k015]
file = %(MOD_PATH)s/k015.py

[pos_expf]
file = %(MOD_PATH)s/pos_expf.py